# Travis CI configuration file for psycopg2

language: python
arch:
    - amd64
    - arm64
matrix:
  include:
    - python: 3.8
    - python: 3.7
    - python: 3.6
    - python: 3.5
    
install:
  - pip install -U pip setuptools wheel
  - pip install .
  - rm -rf psycopg2.egg-info
  - sudo scripts/travis_prepare.sh

script:
  - scripts/travis_test.sh

deploy:
  - provider: script
    script: bash scripts/travis_update_docs.sh
    on:
      branch: master

notifications:
  email: false
